Repository explosion/spacy-layout, pull requests merged in 2025-03, with the labels that each got.

#26 Added a code snippet for visualizing a page
  README.md
Labels: docs

#34 Add support for document index tables
  spacy_layout/layout.py
  tests/data/table_document_index.pdf
  tests/test_general.py
Labels: enhancement, docling

#36 Add as_tuples argument to spaCyLayout.pipe
  README.md
  spacy_layout/layout.py
  tests/test_general.py
Labels: enhancement
